#! /usr/bin/python
from argparse import ArgumentParser, REMAINDER
from sys import exit

if __name__ == '__main__':
	import main
	from program import get_programs

	programs = get_programs()
	pgm_verbs = list(programs.keys())
	pgm_verbs.append('help')

	parser = ArgumentParser()
	parser.add_argument('program', type=str, default='help', choices=pgm_verbs)
	parser.add_argument('prog_args', nargs=REMAINDER)
	args = parser.parse_args()

	if args.program == 'help':
		print(f"usage: {parser.prog} <command> [command_args]")
		print("\ncommand is one of:")
		for name, pgm_class in programs.items():
			print(f'    {name}    {pgm_class().description}')
		exit(1)

	prog = programs[args.program](args.prog_args)()
